# Generated by Django 6.0.6 on 2026-06-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_engineer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineer',
            new_name='EngineerProfile',
        ),
        migrations.AlterModelOptions(
            name='engineerprofile',
            options={'verbose_name': 'Профиль инженера', 'verbose_name_plural': 'Профили инженеров'},
        ),
        migrations.AlterModelOptions(
            name='responsiblepersonprofile',
            options={'verbose_name': 'Профиль ответственного лица', 'verbose_name_plural': 'Профили ответственных лиц'},
        ),
    ]
