# Generated by Django 6.0.6 on 2026-06-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_engineer_engineerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='engineerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='responsiblepersonprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='responsiblepersonprofile',
            name='updated_at',
        ),
    ]
