# Generated by Django 6.0.6 on 2026-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_engineerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
    ]
