# Generated by Django 6.0.6 on 2026-06-11 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_engineer_engineerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HidWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_documentation', models.CharField(blank=True, max_length=255, verbose_name='Рабочая документация')),
                ('hidden_work_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование скрытой работы')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата начала работ')),
                ('finish_date', models.DateTimeField(auto_now=True, verbose_name='Дата окончания работ')),
                ('ResponsiblePersonProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person_profile', to='users.responsiblepersonprofile', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Скрытая работа',
                'verbose_name_plural': 'Скрытые работы',
            },
        ),
    ]
