# Generated by Django 6.0.6 on 2026-06-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidwork',
            name='photo',
            field=models.ImageField(blank=True, upload_to='hid_works/photos/', verbose_name='Фото'),
        ),
    ]
