# Generated by Django 6.0.6 on 2026-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0002_hidwork_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hidwork',
            old_name='hidden_work_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='hidwork',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/hid_works/photos/', verbose_name='Фото'),
        ),
    ]
