# Generated by Django 6.0.6 on 2026-06-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0003_rename_hidden_work_name_hidwork_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidwork',
            name='photo',
            field=models.ImageField(blank=True, upload_to='HidWorks/', verbose_name='Фотографии'),
        ),
    ]
