# Generated by Django 6.0.6 on 2026-06-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0004_alter_hidwork_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidwork',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
    ]
