# Generated by Django 6.0.6 on 2026-06-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0005_hidwork_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidwork',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
    ]
