# Generated by Django 6.0.6 on 2026-06-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0006_hidwork_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidwork',
            name='photo',
        ),
        migrations.CreateModel(
            name='HidWorkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='hid_work_materials/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('hid_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hid_works.hidwork', verbose_name='Материалы сктытой работы')),
            ],
            options={
                'verbose_name': 'Материал скрытой работы',
                'verbose_name_plural': 'Материалы скрытых работ',
            },
        ),
    ]
