# Generated by Django 6.0.6 on 2026-06-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0007_remove_hidwork_photo_hidworkmaterial'),
        ('users', '0003_rename_engineer_engineerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidwork',
            name='ResponsiblePersonProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person_profile', to='users.responsiblepersonprofile', verbose_name='Ответственное лицо'),
        ),
        migrations.AlterField(
            model_name='hidworkmaterial',
            name='hid_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hid_work', to='hid_works.hidwork', verbose_name='Скрытая работа'),
        ),
    ]
