# Generated by Django 6.0.6 on 2026-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0008_alter_hidwork_responsiblepersonprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hidwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hid_work/file'),
        ),
        migrations.AlterField(
            model_name='hidwork',
            name='finish_date',
            field=models.DateTimeField(verbose_name='Дата окончания работ'),
        ),
        migrations.AlterField(
            model_name='hidwork',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала работ'),
        ),
    ]
