# Generated by Django 6.0.6 on 2026-06-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0009_hidwork_file_alter_hidwork_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hid_work/file', verbose_name='Файл'),
        ),
    ]
