# Generated by Django 6.0.6 on 2026-06-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0010_alter_hidwork_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, verbose_name='Шифр')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='hidwork',
            name='working_documentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_documentation', to='hid_works.workingdocumentation', verbose_name='Рабочая документация'),
        ),
    ]
