# Generated by Django 6.0.6 on 2026-06-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0011_workingdocumentation_and_more'),
        ('users', '0003_rename_engineer_engineerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidwork',
            name='ResponsiblePersonProfile',
        ),
        migrations.AddField(
            model_name='hidwork',
            name='responsible_person_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hid_works', to='users.responsiblepersonprofile', verbose_name='Ответственное лицо'),
        ),
        migrations.AlterField(
            model_name='hidwork',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='hidwork',
            name='working_documentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hid_works', to='hid_works.workingdocumentation', verbose_name='Рабочая документация'),
        ),
        migrations.AlterField(
            model_name='hidworkmaterial',
            name='hid_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hid_works.hidwork', verbose_name='Скрытая работа'),
        ),
    ]
