# Generated by Django 6.0.6 on 2026-06-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hid_works', '0012_remove_hidwork_responsiblepersonprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hidworkmaterial',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='hidwork',
            name='file',
        ),
        migrations.RemoveField(
            model_name='hidworkmaterial',
            name='position',
        ),
    ]
