# Generated by Django 6.0.6 on 2026-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('order', 'Приказ'), ('regulation', 'Распоряжение'), ('decree', 'Постановление'), ('instruction', 'Указание')], default='order', verbose_name='Тип документа')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('document_date', models.DateField(auto_now=True, verbose_name='Дата документа')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('basis', models.TextField(blank=True, verbose_name='Основание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Действующий')),
                ('file', models.FileField(blank=True, upload_to='administrative_documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Организационно-распорядительный документ',
                'verbose_name_plural': 'Организационно-распорядительные документы',
                'ordering': ['-document_date'],
            },
        ),
    ]
