# Generated by Django 6.0.6 on 2026-06-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativedocument',
            name='basis',
        ),
        migrations.RemoveField(
            model_name='administrativedocument',
            name='content',
        ),
    ]
