# Generated by Django 6.0.6 on 2026-06-25 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_administrativedocument_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('project', 'Проектная документация'), ('estimate', 'Сметная документация'), ('working', 'Рабочая документация'), ('as_built', 'Исполнительная документация')], default='as_built', verbose_name='Тип документации')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='Шифр документации')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('document_date', models.DateField(auto_now=True, verbose_name='Дата документа')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('technical_specifications', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('estimate_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сметная стоимость')),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Договорная цена')),
                ('file', models.FileField(blank=True, upload_to='project_documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Проектно-сметная документация',
                'verbose_name_plural': 'Проектно-сметная документация',
                'ordering': ['-registration_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='project_documents/attachments/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('project_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.projectdocument', verbose_name='Проектный документ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружен')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
