# Generated by Django 6.0.6 on 2026-06-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_projectdocument_projectdocumentattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDocumentAttachment',
        ),
    ]
